// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: Hero,
  product_grid: ProductGrid,
  rich_text: dynamic(() => import("./RichText")),
};
